.travis.yml, client/components/AppMap.js, client/components/index.js, client/components/navbar.js, client/components/user-home.spec.js, client/routes.js, client/store/user.spec.js, package-lock.json, package.json, public/index.html, public/style.css, script/seed.spec.js, server/api/users.spec.js, server/db/models/user.spec.js
=> added here map

client/components/navbar.js, client/routes.js, package-lock.json, package.json, public/index.html
=> #18-completed

package-lock.json, script/seed.js, server/db/models/address.js, server/db/models/driver.js, server/db/models/index.js, server/db/models/order.js, server/db/models/user.js
=> Define models #29

client/components/AppMap.js, package-lock.json, package.json, public/index.html
installed initial mapbox rendering (in AppMap)
=> mapbox installed

client/components/AppMap.js, client/components/MapRoute.js, client/components/index.js, client/routes.js, package-lock.json, package.json, public/style.css
=> added a direction tab under /route

client/components/AppMap.js, script/seed.js
Added a driver user and a customer user, along with an associated address for the customer and an associated driver for the driver.
=> initial db seed

client/components/MapRoute.js, client/routes.js, public/style.css
=> we have a route in the map when pressing the button

client/routes.js
/appmap now renders AppMap with device location
=> updated appmap url route

client/components/MapRoute.js, client/components/MyPosition.js, client/components/UserMap.js, client/components/constant.js, public/style.css
=> the user can geolocate

client/components/MapRoute.js, client/components/UserMap.js, client/store/index.js, client/store/myLocation.js, client/store/order.js, public/style.css
Just added the current location to the store, so we can use it in any part of the app
=> #13 route to pick up

public/style.css, script/seed.js, server/api/orders.js, server/db/models/driver.js
fixes #4 
Assigns the closest driver to the user that requests a pickup and updates that driver's status to 'Busy'. Also fixes starting location of order to be that of the driver, rather than that of user.
=> assigns driver to user

client/components/MapRoute.js, public/style.css
=> #2-completed-for-mvp

client/store/order.js, server/api/orders.js, server/db/models/driver.js, server/db/models/order.js
Changed up the model to align with Mark's changes, also changed postOrder thunk to accommodate pickup and delivery locations, and send them to express route.
The post order express route now expects a pickuplat, pickuplng, dropofflat, dropofflng, and delivery note from the front end, and pulls driver location from the backend.
=> fixed up postRoute thunk

client/components/auth-form.js, script/seed.js, server/db/models/user.js
=> updated user model and form

server/auth/google.js
=> google oauth online

client/components/UserMap.js
=> add load listener to map

client/components/MapRoute.js, client/components/Me.js, client/components/UserMap.js, client/store/order.js
=> #13 user location

client/routes.js, server/auth/google.js
=> fixes doubel line

client/components/auth-form.js, server/auth/google.js
Fixed Login/Signup With Google button's redirect and updated passport auth to redirect to /me instead of /home upon successful auth
=> fixed google passport button and redirect

client/store/user.js
newly added address **was** STRING, **now** NUMBER
=> fixed-data-type

client/components/DriverMapRoute.js, server/index.js
=> drivers updates his location on the map

client/components/DriverSwitch.js, client/components/MapRoute.js, client/socket.js, server/api/orders.js, server/socket/index.js
=> #68 driver job offered

client/components/AddDefaultAddress.js, client/components/MapRoute.js, client/components/SidebarMenu.js, client/routes.js, client/store/user.js
=> #71-completed

client/routes.js
added a redirect so if some go to .com it will redirect to /me
=> added a redirect route to react router

client/components/DriverMapRoute.js, client/components/MapRoute.js, client/components/Rover.js
=> fixed viewpoint styling and driver map display

script/drivers.js, script/seed.js, script/users.js
run the new seed to see our new 100 drivers :)
=> Drivers lots of drivers

client/components/Archive/loggedinUser.js, client/components/DriverMapRoute.js, client/components/DriverSwitch.js, client/components/MapRoute.js, client/components/UserProfile.js, client/routes.js, client/store/index.js, client/store/user.js
Consolidated LoggedinUser store into User - also default routes logged in users to Me component
=> no more loggedinUser

client/components/Archive/navbar.js, client/components/DriverMapRoute.js, client/components/DriverSwitch.js, client/components/MapRoute.js, client/components/Rover.js, client/components/SidebarMenu.js
=> moved driver switch to sidebar of loggedin driver.

client/socket.js, server/socket/index.js
Added a check to make sure the driver receiving ride requests is one of the intended drivers.
=> Multiple orders at once #92

server/api/orders.js, server/db/models/driver.js
fixes #97 
Migrated find driver function to be a model method
=> migrated helper function to model method

client/components/DriverMapRoute.js, client/components/SidebarMenu.js, client/store/order.js
=> Driver Life Cycle Goes Full Circle

client/components/MapRoute.js, server/api/orders.js
=> must have location before ride can be requested

client/components/DriverSwitch.js, client/components/SidebarMenu.js, client/routes.js, server/api/orders.js, server/auth/index.js
=> #127 fix driver switch

server/api/drivers.js, server/api/middleware.js, server/api/orders.js, server/api/users.js
=> middleware in place, implemented where obvious

server/auth/index.js
=> fixed the bug

client/components/DriverSwitch.js
=> refactor the toggle bar to only have one

client/components/DriverMap.js, client/components/DriverMapRoute.js, client/components/MapRoute.js, client/components/UserMap.js
=> the deriver route is updated on the clinet side

script/seed.js, script/users.js, server/db/models/user.js
Updated seed to fix text notification problem.
=> updated seed for text issues

client/components/DriverMapRoute.js, client/components/MapRoute.js, client/store/driverLocation.js, client/store/index.js, server/api/drivers.js
=> Driver route updates

client/components/DriverInfoCard.js, client/components/MapRoute.js, server/api/orders.js
closes #135 
INFO:
user now knows a little bit about the stranger looking for them
=> THE USER CAN NOW SEE DRIVER DATA IN A NICELY STYLED LIL BOX

client/components/DriverMapRoute.js, client/components/DriverUserItem.js
=> THE DRIVER CAN NOW SEE USER DATA IN A NICELY STYLED LIL BOX

client/components/MapRoute.js, client/components/UserMap.js
=> the timeout doesnt run if there is no driver

client/components/SidebarMenu.js
=> Add user to menu #166
